export const registryAbi = [
  { type: 'function', name: 'register', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'string' }, { type: 'string' }], outputs: [] },
  { type: 'function', name: 'updatePayout', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'address' }], outputs: [] },
  { type: 'function', name: 'updateMetadata', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'string' }, { type: 'string' }], outputs: [] },
  { type: 'function', name: 'exists', stateMutability: 'view',
    inputs: [{ type: 'string' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getPayoutAddress', stateMutability: 'view',
    inputs: [{ type: 'string' }], outputs: [{ type: 'address' }] },
  { type: 'function', name: 'getCreator', stateMutability: 'view',
    inputs: [{ type: 'string' }],
    outputs: [{
      type: 'tuple',
      components: [
        { name: 'payoutAddress', type: 'address' },
        { name: 'registeredAt', type: 'uint256' },
        { name: 'displayName', type: 'string' },
        { name: 'metadataURI', type: 'string' },
        { name: 'verified', type: 'bool' },
      ],
    }],
  },
  { type: 'event', name: 'Registered',
    inputs: [
      { type: 'bytes32', name: 'usernameHash', indexed: true },
      { type: 'string', name: 'username', indexed: false },
      { type: 'address', name: 'payoutAddress', indexed: true },
    ] },
] as const;

export const tipJarAbi = [
  { type: 'function', name: 'tip', stateMutability: 'payable',
    inputs: [{ type: 'string' }, { type: 'string' }], outputs: [] },
  { type: 'function', name: 'tipAddress', stateMutability: 'payable',
    inputs: [{ type: 'address' }, { type: 'string' }], outputs: [] },
  { type: 'function', name: 'getTipsCount', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getLifetimeReceived', stateMutability: 'view',
    inputs: [{ type: 'string' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'getTipsByCreator', stateMutability: 'view',
    inputs: [{ type: 'string' }], outputs: [{ type: 'uint256[]' }] },
  { type: 'function', name: 'getTip', stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'from', type: 'address' },
      { name: 'usernameHash', type: 'bytes32' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
      { name: 'message', type: 'string' },
    ]}],
  },
  { type: 'function', name: 'protocolFeeBps', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'event', name: 'TipSent',
    inputs: [
      { type: 'uint256', name: 'tipId', indexed: true },
      { type: 'bytes32', name: 'usernameHash', indexed: true },
      { type: 'address', name: 'from', indexed: true },
      { type: 'uint256', name: 'netAmount', indexed: false },
      { type: 'uint256', name: 'protocolFee', indexed: false },
      { type: 'string', name: 'message', indexed: false },
    ] },
] as const;

export const subscriptionsAbi = [
  { type: 'function', name: 'createPlan', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'string' }, { type: 'uint256' }, { type: 'string' }],
    outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'subscribe', stateMutability: 'payable',
    inputs: [{ type: 'uint256' }, { type: 'uint256' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'cancel', stateMutability: 'nonpayable',
    inputs: [{ type: 'uint256' }], outputs: [] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }], outputs: [] },
  { type: 'function', name: 'isActive', stateMutability: 'view',
    inputs: [{ type: 'address' }, { type: 'uint256' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getPlan', stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'creatorHash', type: 'bytes32' },
      { name: 'name', type: 'string' },
      { name: 'pricePerMonth', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
      { name: 'active', type: 'bool' },
    ]}],
  },
  { type: 'function', name: 'claimableRevenue', stateMutability: 'view',
    inputs: [{ type: 'string' }], outputs: [{ type: 'uint256' }] },
] as const;

export const contentPaywallAbi = [
  { type: 'function', name: 'createContent', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'bytes32' }, { type: 'uint256' }, { type: 'string' }],
    outputs: [] },
  { type: 'function', name: 'purchase', stateMutability: 'payable',
    inputs: [{ type: 'bytes32' }], outputs: [] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }], outputs: [] },
  { type: 'function', name: 'checkAccess', stateMutability: 'view',
    inputs: [{ type: 'bytes32' }, { type: 'address' }], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'getContent', stateMutability: 'view',
    inputs: [{ type: 'bytes32' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'contentId', type: 'bytes32' },
      { name: 'creatorHash', type: 'bytes32' },
      { name: 'price', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
      { name: 'active', type: 'bool' },
      { name: 'totalSales', type: 'uint256' },
      { name: 'totalRevenue', type: 'uint256' },
    ]}],
  },
] as const;

export const payPerCallAbi = [
  { type: 'function', name: 'registerEndpoint', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }, { type: 'string' }, { type: 'uint256' }],
    outputs: [{ type: 'bytes32' }] },
  { type: 'function', name: 'pay', stateMutability: 'payable',
    inputs: [{ type: 'bytes32' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'payByName', stateMutability: 'payable',
    inputs: [{ type: 'string' }, { type: 'string' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'batchPay', stateMutability: 'payable',
    inputs: [{ type: 'bytes32' }, { type: 'uint256' }], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'withdraw', stateMutability: 'nonpayable',
    inputs: [{ type: 'string' }], outputs: [] },
  { type: 'function', name: 'getEndpointByName', stateMutability: 'view',
    inputs: [{ type: 'string' }, { type: 'string' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'creatorHash', type: 'bytes32' },
      { name: 'name', type: 'string' },
      { name: 'pricePerCall', type: 'uint256' },
      { name: 'active', type: 'bool' },
      { name: 'totalCalls', type: 'uint256' },
      { name: 'totalRevenue', type: 'uint256' },
    ]}],
  },
  { type: 'function', name: 'getReceipt', stateMutability: 'view',
    inputs: [{ type: 'uint256' }],
    outputs: [{ type: 'tuple', components: [
      { name: 'callId', type: 'uint256' },
      { name: 'endpointId', type: 'bytes32' },
      { name: 'payer', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'timestamp', type: 'uint256' },
    ]}],
  },
] as const;
